version: 2.1
orbs:
  node: circleci/node@4.1.1
jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run JEST tests
workflows:
  test_my_app:
    jobs:
      - test
